config/routes.rb
Factcheck::Application.routes.draw do
 
  resources :videos do
    resources :comments
  end

  get "sessions/new"

  get "users/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  match "videos/:id/comments" => "comments#index", :as => "all_comments"
  resources :users
  resources :sessions

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :user_id, :video_id, :time

  belongs_to :user
  belongs_to :video
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :username

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :videos
  has_many :comments

  def self.authenticate(email, password)
  	user = find_by_email(email)
  	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  		user
  	else
  		nil
  	end
  end

  def encrypt_password
  	if password.present?
  		self.password_salt = BCrypt::Engine.generate_salt
  		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  	end
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :title, :url, :user_id

  belongs_to :user
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @video = Video.find(params[:video_id])
    @comments = @video.comments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create

    @video = Video.find(params[:video_id])
    @comment = @video.comments.new(params[:comment])

    

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])

  	if user
  		session[:user_id] = user.id
  		redirect_to videos_path, :notice => "Logged in!"
  	else
  		flash.now.alert = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to videos_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])

  	if @user.save
  		redirect_to new_video_path, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
    @message = Hash.new

    @user = User.find(@video.user_id)

    @substring =  @video.url[-11..@video.url.length]

    @video.comments.each do |c|
      puts "XXXXXXXX" + c.user_id.to_s
      username = User.find(c.user_id).username
      @message[c.time] = Hash[ 'user' => username, 'body' => c.body]
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }#@video.comments }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new

    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :video_id %><br />
    <%= f.number_field :video_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments for <%=link_to @video.title, video_path(@video) %></h1>

<table>
  <tr>
    <th>Time</th>
    <th>Body</th>
    <th>Posted by:</th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><p><%= Time.at(comment.time).gmtime.strftime('%R:%S') %></p></td>
    <td><p><%= comment.body %></p></td>
    <td><p><%= User.find(comment.user_id).username %></p></td>
    <% if comment.user_id = current_user.id %>
      
    <% end %>
  </tr>
<% end %>
</table>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Video:</b>
  <%= @comment.video_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Factcheck</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav">
		<p>
		  <% if current_user %>
		    Logged in as <%= current_user.username %>
		    <%= link_to "Log out", log_out_path %>
		  <% else %>
		    <%= link_to "Sign up", sign_up_path %> or
		    <%= link_to "log in", log_in_path %>
		  <% end %>
	  	</p>
	  	<!-- <p>
	  		<% if current_user %>
	  			<%= link_to 'Edit my profile', edit_user_path(current_user) %>
	  		<% end %>
	  	</p> -->
	</div>

	<div id="content">
	<header>
		<h1>Fact-Check Youtube</h1>
	</header>
		<div id="content-inner">
		<% if request.fullpath != videos_path %>
			<h3><%= link_to "See all videos", videos_path %></h3>
		<% end %>
		
		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>

		<%= yield %>


		
		</div>
	</div>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>All videos</h1>
<% if current_user %>
<h2><%= link_to 'Add Video', new_video_path %></h2>
<% else %>
<h2><%= link_to "Log in", log_in_path %> or <%= link_to "sign up", sign_up_path %> to add a video</h2>
<% end %>

<div id="videos-list">
  <% @videos.each do |video| %>

    <div class="video">
      <h3><%= video.title %></h3>
      <p>
        <%= link_to image_tag("http://img.youtube.com/vi/" + video.url[-11..video.url.length] + "/0.jpg", :height=>160, :width=>200), video %>
      </p>
      <p>
       Comments: <%= video.comments.count %>
      </p>
      <% if current_user %>
        <% if current_user.id == video.user_id %>
          <%= link_to 'Edit', edit_video_path(video) %> |
          <%= link_to 'Delete', video, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h3><%= @video.title %></h3>
</p>

<p>
  <b>Linked by:</b>
  <%= @user.email %>
</p>

<!-- <p>
  <b>Url:</b>
  <%= @video.url %>
</p> -->

<div id="ytapiplayer">
    You will need Flash 8 or better to view this content.
</div>
<br/>
  <% if current_user %>
    <% if current_user.id == @user.id %>
      <%= link_to 'Edit', edit_video_path(@video) %>
    <% end %>
  <% end %>

<% if current_user %>
<button id="saveButton" value="Insert Comment">Insert Message at this point</button>
<% else %>
<p><span id="notLoggedIn">You must log in to post comments</span></p>
<% end %>

<%= link_to 'See all comments', all_comments_path(@video) %>

<div id="message"></div>

<% if current_user %>
  <%=form_for([@video, @video.comments.build], :html => {:id => "saveForm" }) do |f| %>
      <div class="field">
        <%= f.label :time %><br />
        <%= f.text_field :time, :style=>"width:40px;"%> seconds
      </div>

      <div class="field">
        <%= f.label :body %><br />
        <%= f.text_area :body %>
      </div>

      <%= f.hidden_field :video_id, :value => @video.id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
       <input type="button" id="submit_comment" value="Add Comment"></button>
  <% end %>
<% end %>

<script type="text/javascript">
  var params = { allowScriptAccess: "always" };
  var atts = { id: "myytplayer" };
  var speed = 1000;
  var messages = {};

  $(document).ready(function() {
    $("#saveForm").hide();

      $.getJSON(
          'http://localhost:3000/videos/<%= @video.id %>.json',
          function(jsonData) {
            $.each(jsonData, function(key, val) {
              messages[key] = { userfield:val['user'], bodyfield:val['body']};
              //console.log("key:" + key + " Object:" + messages[key])
              // messages.push({time: key, userfield: val['user'], bodyfield: val['body']});

            });
          });

    $('#saveButton').click(function() {
        ytplayer.pauseVideo();
        $("#comment_time").val(Math.floor(ytplayer.getCurrentTime()));
        $("#saveForm").show();
    });

    $('#submit_comment').click(function() {
        var comment_object = {
          'time': $("#comment_time").val(),
          'body': $("#comment_body").val(),
          'user_id': $("#comment_user_id").val(),
        };

        $.ajax({
            url: "/videos/<%=  @video.id %>/comments", //sumbits it to the given url of the form
            data: JSON.stringify(comment_object),
            type: "POST",
            contentType:"application/json",
            dataType: "json", // you want a difference between normal and ajax-calls, and json is standard
            success: function(json){
              videoTime = Math.floor(ytplayer.getCurrentTime());
              
              var newMessage = '<p class="message message' + videoTime + '"><span class="user-name"><%= User.find(current_user.id).username %> :</span><br />"' + $("#comment_body").val() + "</p>";
              $('#message').append(newMessage);

              console.log(json);
              $("#comment_time").val("");
              $("#comment_body").val("");
              ytplayer.playVideo();
              $("#saveForm").hide();
            },
            error: function(jqXHR, textStatus, errorThrown) {
              console.log(textStatus);
              alert("Sorry something went wrong, your message didn't submit");
            }
          });
    });
  });

  swfobject.embedSWF("http://www.youtube.com/v/<%= @substring %>&enablejsapi=1&playerapiid=ytplayer", "ytapiplayer", "425", "365", "8", null, null, params, atts);

  function onYouTubePlayerReady(playerId) {
    ytplayer = document.getElementById("myytplayer");

    if (ytplayer) {
      ytplayer.playVideo();
      
      setInterval(rotate, speed);
    }
  }

  function rotate() {

    if(ytplayer.getPlayerState() != 2){
      videoTime = Math.floor(ytplayer.getCurrentTime());
    
      for(var ii = 0; ii <= (videoTime-10); ii++) {
        $('.message'+ii ).fadeOut();
      }

      for(var k in messages){
        if(k == videoTime){
          var newMessage = '<p class="message message' + videoTime + '"><span class="user-name">' + messages[k]['userfield'] + ":</span><br />" + messages[k]['bodyfield'] + "</p>";

          $('#message').append(newMessage);
        }
      }
    }
  }
</script>